clean:
		-rm mpi
		-rm mp
generate:
		gcc  generator.c  -o generator.out
		./generator.out datafile 15000000
examine:
		mpicc mpi.c -o mpi
		gcc -fopenmp mp.c -o mp
		mpirun -np 2 ./mpi 15000000 -1 datafile -1 -1
		./mp 15000000 -1 datafile -1 -1
all:
		make -f ./MakeFile clean  
		make -f ./MakeFile generate
		make -f ./MakeFile examine
		 
